### ISSUE TITLE
GTFS data importing error TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by danydacosta** [BlinkTagInc/node-gtfs#90] opened 2018-02-08 19:17 UTC
Hi there,

I'm having trouble when importing GTFS using gtfs-import. I have an error `TypeError: Cannot convert undefined or null to object\transit\TransitData\gtfs-downloads/gtfs_swiss-gtfs.zip`. Below is my files:

config.json:

```
{
  "mongoUrl": "mongodb://localhost:27017/gtfs_swiss",
  "agencies": [
    {
      "agency_key": "gtfs_swiss",
      "url": "http://transitfeeds.com/p/sbb-cff-ffs/793/latest/download",
      "exclude": [
        "fare_attributes",
        "fare_rules",
        "feed_info",
        "frequencies",
        "shapes"
      ]
    }
  ]
}
```

gtfs-import output:

```
C:\Users\Dany\Desktop\transit\TransitData>gtfs-import

Starting GTFS import for 1 file
gtfs_swiss: Downloading GTFS from http://transitfeeds.com/p/sbb-cff-ffs/793/latest/download
gtfs_swiss: Download successful
TypeError: Cannot convert undefined or null to object\transit\TransitData\gtfs-downloads/gtfs_swiss-gtfs.zip
    at Function.assign (<anonymous>)
    at executeOperation (C:\Users\Dany\AppData\Roaming\npm\node_modules\gtfs\node_modules\mongodb\lib\utils.js:386:14)
    at Collection.remove (C:\Users\Dany\AppData\Roaming\npm\node_modules\gtfs\node_modules\mongodb\lib\collection.js:1239:10)
    at NativeCollection.(anonymous function) [as remove] (C:\Users\Dany\AppData\Roaming\npm\node_modules\gtfs\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:139:28)
    at Promise.all.models.map.model (C:\Users\Dany\AppData\Roaming\npm\node_modules\gtfs\lib\import.js:54:35)
    at Array.map (<anonymous>)
    at removeData (C:\Users\Dany\AppData\Roaming\npm\node_modules\gtfs\lib\import.js:53:29)
    at Object.module.exports [as import] (C:\Users\Dany\AppData\Roaming\npm\node_modules\gtfs\lib\import.js:324:13)
    at <anonymous>
```

The mongodb connection seems to be ok as gtfs-import successfully created collections in my mongodb database. See image attached

![2018-02-08 20_13_23-mongodb compass community - localhost_27017](https://user-images.githubusercontent.com/23237919/35993092-8d1d0de0-0d0c-11e8-9c64-49adc59e84c5.png)

But it seems that the error occurs when gtfs-import tries to move the data. Any help would greatly be appreciate.

**Comment by danydacosta** [comment] 2018-02-08 19:46
I tried with your example and it still doesn't work :/  same error. My mongodb version: 

```
db version v3.6.2
git version: 489d177dbd0f0420a8ca04d39fd78d0a2c539420
OpenSSL version: OpenSSL 1.0.1u-fips  22 Sep 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: 2008plus-ssl
    distarch: x86_64
    target_arch: x86_64
```

**Comment by brendannee** [comment] 2018-02-08 20:05
Its failing on this line:
https://github.com/BlinkTagInc/node-gtfs/blob/master/lib/import.js#L54

can you try running it with the --skipDelete option to see if that gets
past this line?

Can you tell me the version of node.js you are running?

Also, it may help to delete the node_modules folder for your project and
reinstall all modules for your project.

**Comment by danydacosta** [comment] 2018-02-08 20:28
Nice it worked with the `--skipDelete` option. Thanks for keeping this repo updated, very useful! 👍 But oddly, it still doesn't work when using `--skipDelete`. I'm using Node v8.9.4.

**Comment by brendannee** [comment] 2018-02-08 21:24
Do you mean it doesn't work without using the --skipDelete? Was it able to fully import?

You are up to date on mongo and node, so I'm wondering if it is a windows issue - I'm on OS X.

I'll keep an eye out for others with the same issue. It could also be something related to mongoose which could be resolved in future versions.

**Comment by danydacosta** [comment] 2018-02-09 09:37
Yeah sorry I made a mistake. It doesn't work **without** `--skipDelete` . He was able to fully import into mongodb. Indeed, I'm on Windows 10.

Thank you again!

**Comment by andreasvirkus** [comment] 2018-02-22 20:47
Having the same issue on Win10 (and only without `--skipDelete`). Can try the same code tomorrow on an OSX and will report back.

**Comment by brendannee** [comment] 2018-02-22 22:04
Thanks for the additional report @andreasvirkus 

This is very likely due to moving to Mongoose 5.0.

Did you just try this using node-gtfs version 1.5.1? I updated mongoose to the latest version 5.0.6 hoping that it might fix this windows specific issue.

I need to get a windows machine to try this out and see what is going on.

In the mean time, I think node-gtfs version 1.4.0 should work for you - can you let me know if it does?

Specifically, the issue is coming from this line: https://github.com/BlinkTagInc/node-gtfs/blob/master/lib/import.js#L53 - if you want to poke around and add some console.logs to see what exactly is going on in that step.

**Comment by andreasvirkus** [comment] 2018-02-23 10:24
Yup I'm using `1.5.1` and `5.0.6` for mongoose
https://github.com/andreasvirkus/tallinn-transport-api/blob/master/package.json#L27

Same code works fine on OSX (`10.12.6`)

If there's anything else I can do to help debug this on Windows, let me know!

Also thanks for the great (**great**) project!

Andreas

**Comment by brendannee** [comment] 2018-03-02 01:29
I think this issue will be resolved in the next release of mongoose that will use mongodb 3.0.3 - I'll keep and eye on this and update node-gtfs as soon as it is released. Specifically, this commit: https://github.com/mongodb/node-mongodb-native/commit/934a43a90141fbacebd4bcdd9151a4f6a8a8bc57

**Comment by brendannee** [comment] 2018-03-06 07:23
Checkout node-gtfs version 1.5.3 - it has an update to mongoose which has an update to the mongodb library which I think will fix your issue on windows. Please report back - thanks!

**Comment by DevinPacker** [comment] 2018-03-06 23:17
@brendannee I was having the same issue with node-gtfs version 1.5.1 on Ubuntu. I can confirm that (for myself at least) upgrading to version 1.5.3 has fixed this issue. I no longer need `skipDelete: true` in my config.

**Comment by brendannee** [comment] 2018-03-06 23:28
Great - closing this issue.

**Closed by brendannee** 2018-03-06 23:28 UTC
