### ISSUE TITLE
Working with Docker Database locked

### ISSUE THREAD

**Issue by AvidDabbler** [BlinkTagInc/node-gtfs#138] opened 2023-03-26 13:53 UTC
First off I know that I should not be using this in production.

I have been fairly successful with working with node-gtfs so far. I have it working with multiple agencies in a realtime backup scenario and it has been fairly bullet proof for the past year.

Recently I have been wanting to add a couple more features with schedule processes and wanted to dockerize my app. I have been able to get it up and running and can get the gtfs to import into the db, but every time I try to query the database, it states that it is locked.

I have added the folder that the db's are in as a volume and even tried adding a NFS configuration for it to see if that would remove the lock and installed sqlite into the container, but I am still having issues with it. 

Has anyone been able to get this working correctly with Docker?

```
FROM node:16-alpine as base

WORKDIR /home/node/backup

# update all the things
RUN apk update
RUN apk add --upgrade apk-tools

# install sqlite tooling
RUN apk add --no-cache sqlite 
RUN apk add  --no-cache socat

COPY package.json ./

RUN npm i

COPY . .

FROM base as production

VOLUME [ "/" ]

ENV NODE_PATH=./build

RUN npm run build

RUN prisma generate
```

**Comment by anbraten** [comment] 2024-03-08 23:55
I think the issue is that `importGtfs` / the cli is only opening databases and never closing it by default. This is somehow necessary to use in-memory correctly, but introduces issues like the one you have mentioned.

**Comment by brendannee** [comment] 2024-03-12 18:51
Thanks for bringing this up.

Would this change: https://github.com/BlinkTagInc/node-gtfs/commit/f13c5687d3bd8d3f5bfad38c4ce2c41dbd93bf93 solve this issue?

It updated the CLI script to close the db after import if it's not an in memory database.  If this looks good, I'll merge it in.

**Comment by anbraten** [comment] 2024-03-12 19:33
That should do it

**Closed** 2024-03-12 19:52 UTC
